FROM python:3.9-slim

# Install virtualenv and create a virtual environment
RUN pip install --no-cache-dir virtualenv==20.6.0 && virtualenv /env --python=python3.9
ENV PATH /env/bin:$PATH

# Install requirements
WORKDIR /app
COPY . .
RUN /env/bin/pip install --no-cache-dir . && \
    apt-get update && apt-get install -y --no-install-recommends nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure nginx
COPY nginx.conf /etc/nginx/sites-available/default

# Copy app, generate static and set permissions
RUN /env/bin/python manage.py collectstatic --no-input --settings=carona_parque.settings.base && \
    chown -R www-data:www-data /app

# Expose and run app
EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["/app/start-server.sh"]
